name: Build Android APK
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Build APK
        uses: pmaru/build-android-apk@-v1.0
        with:
          # إذا كان موقعك يحتاج لرابط معين أو إعدادات خاصة
          app_name: "Saree3"
          app_id: "com.brazili.saree3"
