name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Bubblewrap
        run: |
          npm install -g @bubblewrap/cli
          # هذا الأمر يقوم بتحويل موقعك لـ APK بشكل سريع
          bubblewrap build --skip-pwa-check
